apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-dep
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: mfilahi/mfilahi_app:v1
          ports:
            - containerPort: 1337