# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

# Vm 1
  config.vm.define "asalahS" do |master|
    master.vm.provider "virtualbox" do |vb|
      vb.name = "asalahS"
    end
    master.vm.hostname = "asalahS"
    master.vm.network "private_network", ip: "192.168.42.110"
    master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
    master.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/id_rsa"
    master.vm.provision "file", source: "./confs/app1.yaml", destination: "/tmp/app1.yaml"
    master.vm.provision "file", source: "./confs/app2.yaml", destination: "/tmp/app2.yaml"
    master.vm.provision "file", source: "./confs/app3.yaml", destination: "/tmp/app3.yaml"
    master.vm.provision "file", source: "./confs/ingress.yaml", destination: "/tmp/ingress.yaml"
    master.vm.provision "file", source: "./confs/svc.yaml", destination: "/tmp/svc.yaml"
    master.vm.provision "shell",  path: "scripts/master.sh"
  end

end